# Generated by Django 5.2.10 on 2026-02-05 15:04

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_course_options_alter_lesson_options_and_more"),
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-payment_date"],
                "verbose_name": "платеж",
                "verbose_name_plural": "платежи",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                default="pending", max_length=50, verbose_name="статус оплаты"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID цены Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID продукта Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии Stripe"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.course",
                verbose_name="оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.lesson",
                verbose_name="оплаченный урок",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="email"),
        ),
    ]
